<div class="d-flex justify-content-center">
		<h3 class="font-weight-bold text-center">Ideas</h3>
		<button class="btn btn-outline-dark ml-3" id="idea_container"> <i class="fa fa-lightbulb-o" aria-hidden="true"></i>+</button> &nbsp;&nbsp;
    </div><hr>

	<div id="idea_add" class="m-5">
		<div id="idea_status" class="ml-3 mr-3"></div>
		<form method="POST" action="">
			<label for="sector-input">Sector</label>
			<input list="brow" class="form-control mb-3" id="sector-input" placeholder="- Select idea Industory/Sector -">
			<datalist id="brow">
				<option value="Accountants"></option>
				<option value="Advertising/Public Relations"></option>
				<option value="Aerospace, Defense Contractors"></option>
				<option value="Agribusiness"></option>
				<option value="Agricultural Services & Products"></option>
				<option value="Agriculture"></option>
				<option value="Air Transport"></option>
				<option value="Air Transport Unions"></option>
				<option value="Airlines"></option>
				<option value="Alcoholic Beverages"></option>
				<option value="Alternative Energy Production & Services"></option>
				<option value="Architectural Services"></option>
				<option value="Attorneys/Law Firms"></option>
				<option value="Auto Manufacturers"></option>
				<option value="Banking, Mortgage"></option>
				<option value="Banks, Commercial"></option>
				<option value="Banks, Savings & Loans"></option>
				<option value="Bars & Restaurants"></option>
				<option value="Beer, Wine & Liquor"></option>
				<option value="Books, Magazines & Newspapers"></option>
				<option value="Broadcasters, Radio/TV"></option>
				<option value="Builders/General Contractors"></option>
				<option value="Builders/Residential"></option>
				<option value="Building Materials & Equipment"></option>
				<option value="Building Trade Unions"></option>
				<option value="Business Associations"></option>
				<option value="Business Services"></option>
				<option value="Cable & Satellite TV Production & Distribution"></option>
				<option value="Candidate Committees"></option>
				<option value="Candidate Committees, Democratic"></option>
				<option value="Candidate Committees, Republican"></option>
				<option value="Car Dealers"></option>
				<option value="Car Dealers, Imports"></option>
				<option value="Car Manufacturers"></option>
				<option value="Casinos / Gambling"></option>
				<option value="Cattle Ranchers/Livestock"></option>
				<option value="Chemical & Related Manufacturing"></option>
				<option value="Chiropractors"></option>
				<option value="Civil Servants/Public Officials"></option>
				<option value="Clergy & Religious Organizations"></option>
				<option value="Clothing Manufacturing"></option>
				<option value="Coal Mining"></option>
				<option value="Colleges, Universities & Schools"></option>
				<option value="Commercial Banks"></option>
				<option value="Commercial TV & Radio Stations"></option>
				<option value="Communications/Electronics"></option>
				<option value="Computer Software"></option>
				<option value="Conservative/Republican"></option>
				<option value="Construction"></option>
				<option value="Construction Services"></option>
				<option value="Construction Unions"></option>
				<option value="Credit Unions"></option>
				<option value="Crop Production & Basic Processing"></option>
				<option value="Cruise Lines"></option>
				<option value="Cruise Ships & Lines"></option>
				<option value="Dairy"></option>
				<option value="Defense"></option>
				<option value="Defense Aerospace"></option>
				<option value="Defense Electronics"></option>
				<option value="Defense/Foreign Policy Advocates"></option>
				<option value="Democratic Candidate Committees"></option>
				<option value="Democratic Leadership PACs"></option>
				<option value="Democratic/Liberal"></option>
				<option value="Dentists"></option>
				<option value="Doctors & Other Health Professionals"></option>
				<option value="Drug Manufacturers"></option>
				<option value="Education"></option>
				<option value="Electric Utilities"></option>
				<option value="Electronics Manufacturing & Equipment"></option>
				<option value="Electronics, Defense Contractors"></option>
				<option value="Energy & Natural Resources"></option>
				<option value="Entertainment Industry"></option>
				<option value="Environment"></option>
				<option value="Farm Bureaus"></option>
				<option value="Farming"></option>
				<option value="Finance / Credit Companies"></option>
				<option value="Finance, Insurance & Real Estate"></option>
				<option value="Food & Beverage"></option>
				<option value="Food Processing & Sales"></option>
				<option value="Food Products Manufacturing"></option>
				<option value="Food Stores"></option>
				<option value="For-profit Education"></option>
				<option value="For-profit Prisons"></option>
				<option value="Foreign & Defense Policy"></option>
				<option value="Forestry & Forest Products"></option>
				<option value="Foundations, Philanthropists & Non-Profits"></option>
				<option value="Funeral Services"></option>
				<option value="Gambling & Casinos"></option>
				<option value="Gambling, Indian Casinos"></option>
				<option value="Garbage Collection/Waste Management"></option>
				<option value="Gas & Oil"></option>
				<option value="Gay & Lesbian Rights & Issues"></option>
				<option value="General Contractors"></option>
				<option value="Government Employee Unions"></option>
				<option value="Government Employees"></option>
				<option value="Health"></option>
				<option value="Health Professionals"></option>
				<option value="Health Services/HMOs"></option>
				<option value="Hedge Funds"></option>
				<option value="HMOs & Health Care Services"></option>
				<option value="Home Builders"></option>
				<option value="Hospitals & Nursing Homes"></option>
				<option value="Hotels, Motels & Tourism"></option>
				<option value="Human Rights"></option>
				<option value="Ideological/Single-Issue"></option>
				<option value="Industrial Unions"></option>
				<option value="Insurance"></option>
				<option value="Internet"></option>
				<option value="IT"></option>
				<option value="Internet Of Things (IoT)"></option>
				<option value="Labor"></option>
				<option value="Lawyers & Lobbyists"></option>
				<option value="Lawyers / Law Firms"></option>
				<option value="Leadership PACs"></option>
				<option value="Liberal/Democratic"></option>
				<option value="Liquor, Wine & Beer"></option>
				<option value="Livestock"></option>
				<option value="Lobbyists"></option>
				<option value="Lodging / Tourism"></option>
				<option value="Logging, Timber & Paper Mills"></option>
				<option value="Manufacturing, Misc"></option>
				<option value="Marine Transport"></option>
				<option value="Meat processing & products"></option>
				<option value="Medical Supplies"></option>
				<option value="Mining"></option>
				<option value="Misc Business"></option>
				<option value="Misc Finance"></option>
				<option value="Misc Manufacturing & Distributing"></option>
				<option value="Misc Unions"></option>
				<option value="Miscellaneous Defense"></option>
				<option value="Miscellaneous Services"></option>
				<option value="Mortgage Bankers & Brokers"></option>
				<option value="Motion Picture Production & Distribution"></option>
				<option value="Music Production"></option>
				<option value="Natural Gas Pipelines"></option>
				<option value="Newspaper, Magazine & Book Publishing"></option>
				<option value="Non-profits, Foundations & Philanthropists"></option>
				<option value="Nurses"></option>
				<option value="Nursing Homes/Hospitals"></option>
				<option value="Nutritional & Dietary Supplements"></option>
				<option value="Oil & Gas"></option>
				<option value="Other"></option>
				<option value="Payday Lenders"></option>
				<option value="Pharmaceutical Manufacturing"></option>
				<option value="Pharmaceuticals / Health Products"></option>
				<option value="Phone Companies"></option>
				<option value="Physicians & Other Health Professionals"></option>
				<option value="Postal Unions"></option>
				<option value="Poultry & Eggs"></option>
				<option value="Power Utilities"></option>
				<option value="Printing & Publishing"></option>
				<option value="Private Equity & Investment Firms"></option>
				<option value="Professional Sports, Sports Arenas & Related Equipment & Services"></option>
				<option value="Progressive/Democratic"></option>
				<option value="Public Employees"></option>
				<option value="Public Sector Unions"></option>
				<option value="Publishing & Printing"></option>
				<option value="Radio/TV Stations"></option>
				<option value="Railroads"></option>
				<option value="Real Estate"></option>
				<option value="Record Companies/Singers"></option>
				<option value="Recorded Music & Music Production"></option>
				<option value="Recreation / Live Entertainment"></option>
				<option value="Religious Organizations/Clergy"></option>
				<option value="Residential Construction"></option>
				<option value="Restaurants & Drinking Establishments"></option>
				<option value="Retail Sales"></option>
				<option value="Savings & Loans"></option>
				<option value="Schools/Education"></option>
				<option value="Sea Transport"></option>
				<option value="Securities & Investment"></option>
				<option value="Special Trade Contractors"></option>
				<option value="Sports, Professional"></option>
				<option value="Steel Production"></option>
				<option value="Stock Brokers/Investment Industry"></option>
				<option value="Student Loan Companies"></option>
				<option value="Sugar Cane & Sugar Beets"></option>
				<option value="Teachers Unions"></option>
				<option value="Teachers/Education"></option>
				<option value="Telecom Services & Equipment"></option>
				<option value="Telecommunication"></option>
				<option value="Telephone Utilities"></option>
				<option value="Textiles"></option>
				<option value="Timber, Logging & Paper Mills"></option>
				<option value="Tobacco"></option>
				<option value="Transportation"></option>
				<option value="Transportation Unions"></option>
				<option value="Trash Collection/Waste Management"></option>
				<option value="Trucking"></option>
				<option value="TV / Movies / Music"></option>
				<option value="TV Production"></option>
				<option value="Unions"></option>
				<option value="Unions, Airline"></option>
				<option value="Unions, Building Trades"></option>
				<option value="Unions, Industrial"></option>
				<option value="Unions, Misc"></option>
				<option value="Unions, Public Sector"></option>
				<option value="Unions, Teacher"></option>
				<option value="Unions, Transportation"></option>
				<option value="Universities, Colleges & Schools"></option>
				<option value="Vegetables & Fruits"></option>
				<option value="Venture Capital"></option>
				<option value="Waste Management"></option>
				<option value="Wine, Beer & Liquor"></option>
				<option value="Women's Issues"></option>
			</datalist> 
			<label for="idea_name">idea name</label>
			<input type="name" id="idea_name" placeholder="Idea name" class="form-control mb-3">
			<label for="idea_trademark">idea trademark</label>
			<input type="name" id="idea_trademark" placeholder="Idea trademark (Strickly copied from the idea summary)" class="form-control mb-3">
			<label class="mb-3 font-italic text-danger">Nature of idea(<span id="nature-char-left">2000 Characters</span>)</label>
			<textarea style="height: 150px; resize: none;" class="form-control" id="idea_nature" maxlength="2000" placeholder="Idea nature"></textarea>
			<label class="mb-3 font-italic text-danger">Target market(<span id="market-char-left">1000 Characters</span>)</label>
			<textarea style="height: 150px; resize: none;" class="form-control" id="idea_target_market" maxlength="1000" placeholder="Idea target market"></textarea>
			<div class="mt-3">
				<button type="submit" class="btn btn-primary float-right" id="register_idea">Save <i class="fa fa-save"></i></button>
			</div>

		</form>
	</div>